import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { type NextPage } from "next";
import Head from "next/head";
import JournalList from "../components/JournalList";
import NewJournal from "../components/NewJournal";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Group Prayer Journal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={2}>
        <Typography variant="h3">Journals</Typography>
        <JournalList />
        <NewJournal />
      </Stack>
    </>
  );
};

export default Home;
