import AppBar from "@mui/material/AppBar";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Container from "@mui/system/Container";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { AuthButton } from "./AuthButton";
import { CustomThemeProvider } from "./CustomThemeProvider";

export const Layout: React.FC<React.PropsWithChildren> = ({ children }) => {
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Group Prayer Journal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomThemeProvider>
        <CssBaseline />
        <AppBar position="static">
          <Toolbar>
            <Link href="/" style={{ flexGrow: 1 }}>
              <Typography variant="h6" component="div">
                Group Prayer Journal
              </Typography>
            </Link>
            <AuthButton />
          </Toolbar>
        </AppBar>
        <Container maxWidth="md" sx={{ mt: 2 }}>
          {status === "unauthenticated" ? (
            <Typography variant="h3">Sign in to use the application</Typography>
          ) : null}
          {status === "authenticated" ? children : null}
        </Container>
      </CustomThemeProvider>
    </>
  );
};
